@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.2 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
<<<<<<< HEAD
REM Generated by Vivado on Tue Mar 03 00:15:17 -0600 2026
=======
REM Generated by Vivado on Mon Mar 02 22:05:57 -0600 2026
>>>>>>> 096fc132465c5e18917bdd794d92422775f17520
REM SW Build 6299465 on Fri Nov 14 19:35:11 GMT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: compile.bat
REM
REM ****************************************************************************
set SIM_VER_XSIM=
set GCC_VER_XSIM=9.3.0

REM compile Verilog/System Verilog design sources
<<<<<<< HEAD
echo "xvlog --incr --relax -L uvm -prj oneshot_tb_vlog.prj"
call xvlog  --incr --relax -L uvm -prj oneshot_tb_vlog.prj -log xvlog.log
=======
echo "xvlog --incr --relax -L uvm -prj debouncer_tb_vlog.prj"
call xvlog  --incr --relax -L uvm -prj debouncer_tb_vlog.prj -log xvlog.log
>>>>>>> 096fc132465c5e18917bdd794d92422775f17520
call type xvlog.log > compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
