@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
<<<<<<< HEAD
REM Generated by Vivado on Tue Mar 03 00:15:27 -0600 2026
=======
REM Generated by Vivado on Mon Mar 02 22:06:02 -0600 2026
>>>>>>> 096fc132465c5e18917bdd794d92422775f17520
REM SW Build 6299465 on Fri Nov 14 19:35:11 GMT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
set SIM_VER_XSIM=
set GCC_VER_XSIM=9.3.0
REM simulate design
<<<<<<< HEAD
echo "xsim oneshot_tb_behav -key {Behavioral:sim_1:Functional:oneshot_tb} -tclbatch oneshot_tb.tcl -log simulate.log"
call xsim  oneshot_tb_behav -key {Behavioral:sim_1:Functional:oneshot_tb} -tclbatch oneshot_tb.tcl -log simulate.log
=======
echo "xsim debouncer_tb_behav -key {Behavioral:sim_1:Functional:debouncer_tb} -tclbatch debouncer_tb.tcl -log simulate.log"
call xsim  debouncer_tb_behav -key {Behavioral:sim_1:Functional:debouncer_tb} -tclbatch debouncer_tb.tcl -log simulate.log
>>>>>>> 096fc132465c5e18917bdd794d92422775f17520
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
